application: directory
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /css
  static_dir:  frontend/css
- url: /fonts
  static_dir: frontend/fonts
- url: /js
  static_dir: frontend/js

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"